[build]
  publish = "dist"
  command = "npm run build"

[build.processing.html]
  pretty_urls = false

# API routes configuration for Astro
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-:splat"
  status = 200

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
